// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:359050340243:web:ed0b976e3aaeb950de2a66',
    messagingSenderId: '359050340243',
    projectId: 'smarttimerplug',
    authDomain: 'smarttimerplug.firebaseapp.com',
    storageBucket: 'smarttimerplug.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:359050340243:android:0fdcdd578faeef48de2a66',
    messagingSenderId: '359050340243',
    projectId: 'smarttimerplug',
    storageBucket: 'smarttimerplug.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:359050340243:ios:36a319b5859a3e65de2a66',
    messagingSenderId: '359050340243',
    projectId: 'smarttimerplug',
    storageBucket: 'smarttimerplug.firebasestorage.app',
    iosBundleId: 'com.edp.timerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:359050340243:ios:36a319b5859a3e65de2a66',
    messagingSenderId: '359050340243',
    projectId: 'smarttimerplug',
    storageBucket: 'smarttimerplug.firebasestorage.app',
    iosBundleId: 'com.edp.timerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '1:359050340243:web:96d4c27f211cfc36de2a66',
    messagingSenderId: '359050340243',
    projectId: 'smarttimerplug',
    authDomain: 'smarttimerplug.firebaseapp.com',
    storageBucket: 'smarttimerplug.firebasestorage.app',
  );
}
